/******************************************************************************/
/*                                                                            */
/*  Copyright(C) 2016, Takao Abe.  All rights reserved.                       */
/*                                                                            */
/*  LICENSE: GPLv3 or any later version                                       */
/*                                                                            */
/******************************************************************************/
/*                                                                            */
/*  ChangeLog                                                                 */
/*                                                                            */
/*  2016/05/21  1.00                                                          */
/*      First release                                                         */
/*                                                                            */
/*  2016/07/02  1.01                                                          */
/*      [Enhancement] Support GNU build procedure.                            */
/*                    Add config.h generated by the Autoconf/Automake.        */
/*                                                                            */
/*  2018/01/14  1.04                                                          */
/*      [Change] Change leaf node anchors have every two characters of the    */
/*               beginning of the domain node name, from they have every one  */
/*               character of the beginning of the domain node name.          */
/*               milter-blockdomain.h  blkdom_check.c  blkdom_config.c        */
/*                                                                            */
/******************************************************************************/

#include "config.h"	/* GNU Autotools */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>

#include "milter-blockdomain.h"

/* External data */

extern	confType xConfData ;
extern	domainListType	xDomainList[ MAX_DOMAIN_LIST ] ;

/**************************************************************************************************/

static bool checkDomain( bool bSubdomain, domainNodeType *pDomainRoot, char *pDomainNodeName[], const int iDomainLevel )
{

	domainLeafType	*pLeafEntry ;
	domainNodeType	*pNodeEntry, *pParentNode ;
	int 	i, iFirstLetterIndex, iSecondLetterIndex ;

	pParentNode = pDomainRoot ;

	for ( i = 0 ; i < iDomainLevel ; i ++ ) {

		iFirstLetterIndex = GET_INDEX( *(pDomainNodeName[i]) ) ;
		iSecondLetterIndex = GET_INDEX( *(pDomainNodeName[i]+1) ) ;

		if ( bSubdomain || i == iDomainLevel - 1 ) {
			pLeafEntry = pParentNode->pLeafList[iFirstLetterIndex][iSecondLetterIndex] ;
			while ( pLeafEntry != NULL ) {
				if ( strcmp( pDomainNodeName[i], pLeafEntry->pName ) == 0 ) {
					/* Found */
					if ( xConfData.bDebugCheckFunction ) {
						logDebug( "%s: Level=%d (Leaf) %s : Match", __func__, i + 1, pLeafEntry->pName ) ;
					}
					return TRUE ;
				} else if ( strcmp( pDomainNodeName[i], pLeafEntry->pName ) < 0 ) {
					/* Not found */
					if ( i == iDomainLevel - 1 ) return FALSE ;
					break ;
				}
				pLeafEntry = pLeafEntry->pNext ;
			}
			if ( i == iDomainLevel - 1 ) return FALSE ;
		}

		pNodeEntry = pParentNode->pNodeList[iFirstLetterIndex] ;
		while ( pNodeEntry != NULL ) {
			if ( strcmp( pDomainNodeName[i], pNodeEntry->pName ) == 0 ) {
				/* Found */
				if ( xConfData.bDebugCheckFunction ) {
					logDebug( "%s: Level=%d (Node) %s : Match", __func__, i + 1, pNodeEntry->pName ) ;
				}
				pParentNode = pNodeEntry ;
				break ;
			} else if ( strcmp( pDomainNodeName[i], pNodeEntry->pName ) < 0 ) {
				/* Not found */
				pNodeEntry = NULL ;
				break ;
			}
			pNodeEntry = pNodeEntry->pNext ;
		}
		if ( pNodeEntry == NULL ) return FALSE ;

	}

	return FALSE ;

}

/**************************************************************************************************/

int checkFQDN( const char *sFQDN )
{

	int 	i ;
	char	sDomainName[ MAX_DOMAIN_NAME_LENGTH + 1 ] ;
	int 	iLength ;
	char	*pDomainNodeName[ MAX_DOMAIN_LEVEL ] ;
	int 	iDomainLevel ;

	if ( sFQDN == NULL ) return RC_NOTLISTED ;
	if ( *sFQDN == 0   ) return RC_NOTLISTED ;

	strncpy( sDomainName, sFQDN, MAX_DOMAIN_NAME_LENGTH ) ;
	sDomainName[MAX_DOMAIN_NAME_LENGTH] = 0 ;
	strLower( sDomainName ) ;
	iLength = strlen( sDomainName ) ;

	if ( sDomainName[0] == '[' && sDomainName[iLength-1] == ']' ) return RC_NOTLISTED ;

	/* Parse domain level */
	iDomainLevel = 0 ;
	for  ( i = iLength - 1 ; i >= 0 ; i -- ) {
		if ( sDomainName[i] == '.' || i == 0 ) {

			if ( iDomainLevel == MAX_DOMAIN_LEVEL ) {
				return RC_NOTLISTED ;
			}

			if ( sDomainName[i] == '.' ) pDomainNodeName[iDomainLevel] = sDomainName + i + 1 ;
			else                         pDomainNodeName[iDomainLevel] = sDomainName + i ;

			if ( strlen( pDomainNodeName[iDomainLevel] ) == 0 ) {
				return RC_NOTLISTED ;
			}

			iDomainLevel ++ ;
			if ( sDomainName[i] == '.' ) sDomainName[i] = 0 ;

		}
	}

	for ( i = 0 ; i < MAX_DOMAIN_LIST ; i ++ ) {
		if ( xDomainList[i].sFileName == NULL ) break ;

		if ( xConfData.bDebugCheckFunction ) logDebug( "%s: %s %s", __func__, sFQDN, xDomainList[i].sFileName ) ;

		if ( checkDomain( xDomainList[i].bSubdomain, &(xDomainList[i].oDomainRoot), pDomainNodeName, iDomainLevel ) ) {
			switch ( xDomainList[i].iListType ) {
			case WHITELIST : return RC_WHITELIST ;
			case BLACKLIST : return RC_BLACKLIST ;
			case GREYLIST  : return RC_GREYLIST ;
			}
		}

	}

	return RC_NOTLISTED ;

}

/**************************************************************************************************/

int checkConnect( const char *sConnect )
{

	int 	rc ;

	rc = checkFQDN( sConnect ) ;
	if ( xConfData.bDebugCheckFunction ) logDebug( "%s: return=%d sConnect=%s", __func__, rc, sConnect ) ;
	return checkFQDN( sConnect ) ;

}

/**************************************************************************************************/

int checkHelo( const char *sHelo )
{

	int 	rc ;

	rc = checkFQDN( sHelo ) ;
	if ( xConfData.bDebugCheckFunction ) logDebug( "%s: return=%d sHelo=%s", __func__, rc, sHelo ) ;
	return rc ;

}

/**************************************************************************************************/

int checkEnvFrom( const char *sEnvFrom )
{

	const char	*pCharLT, *pCharGT, *pCharAtmark ;
	char	sFQDN[ MAX_DOMAIN_NAME_LENGTH + 1 ] ;
	int 	iLength ;
	int 	rc ;

	if ( sEnvFrom == NULL ) return RC_NOTLISTED ;
	if ( *sEnvFrom == 0   ) return RC_NOTLISTED ;

	pCharLT = strchr( sEnvFrom, '<' ) ;
	if ( pCharLT == NULL ) return RC_NOTLISTED ;

	pCharGT = strchr( pCharLT, '>' ) ;
	if ( pCharGT == NULL ) return RC_NOTLISTED ;

	if ( strcmp( pCharLT, "<>" ) == 0 ) return RC_NOTLISTED ;

	pCharAtmark = strchr( pCharLT, '@' ) ;
	if ( pCharAtmark == NULL ) pCharAtmark = pCharLT ;

	strncpy( sFQDN, pCharAtmark + 1, MAX_DOMAIN_NAME_LENGTH ) ;
	sFQDN[MAX_DOMAIN_NAME_LENGTH] = 0 ;
	iLength = strlen( sFQDN ) ;
	if ( sFQDN[iLength-1] == '>' ) sFQDN[iLength-1] = 0 ;

	rc = checkFQDN( sFQDN ) ;
	if ( xConfData.bDebugCheckFunction ) logDebug( "%s: return=%d sFQDN=%s sEnvFrom=%s", __func__, rc, sFQDN, sEnvFrom ) ;
	return rc ;

}

/**************************************************************************************************/

int checkEnvRcpt( const char *sEnvRcpt )
{

	const char	*pCharLT, *pCharGT, *pCharAtmark ;
	char	sFQDN[ MAX_DOMAIN_NAME_LENGTH + 1 ] ;
	int 	iLength ;
	int 	rc ;

	if ( sEnvRcpt == NULL ) return RC_NOTLISTED ;
	if ( *sEnvRcpt == 0   ) return RC_NOTLISTED ;

	pCharLT = strchr( sEnvRcpt, '<' ) ;
	if ( pCharLT == NULL ) return RC_NOTLISTED ;

	pCharGT = strchr( pCharLT, '>' ) ;
	if ( pCharGT == NULL ) return RC_NOTLISTED ;

	if ( strcmp( pCharLT, "<>" ) == 0 ) return RC_NOTLISTED ;

	pCharAtmark = strchr( pCharLT, '@' ) ;
	if ( pCharAtmark == NULL ) pCharAtmark = pCharLT ;

	strncpy( sFQDN, pCharAtmark + 1, MAX_DOMAIN_NAME_LENGTH ) ;
	sFQDN[MAX_DOMAIN_NAME_LENGTH] = 0 ;
	iLength = strlen( sFQDN ) ;
	if ( sFQDN[iLength-1] == '>' ) sFQDN[iLength-1] = 0 ;

	rc = checkFQDN( sFQDN ) ;
	if ( xConfData.bDebugCheckFunction ) logDebug( "%s: return=%d sFQDN=%s sEnvRcpt=%s", __func__, rc, sFQDN, sEnvRcpt ) ;
	return rc ;

}

/**************************************************************************************************/
